### ISSUE TITLE
Hypixel Skyblock Wiki Tools URL errors.

### ISSUE THREAD

**Issue by LogischerJonasHD** [skyblock-wiki/skyblock-wiki.github.io#1]
The page just released and I have already found something!
When visiting the SkyBlock Wiki Tools page (https://skyblock-wiki.github.io), the following buttons do not work due to a messed up URL:
![image](https://user-images.githubusercontent.com/58107194/122784037-64acf400-d2b2-11eb-96bd-d24c4d7ecc4d.png)
_(Marked in red)_

Somehow the URL you are getting redirected to has "https://skyblock-wiki.github.io/downloads/" placed before it (wich does not even lead to anything eather).
![image](https://user-images.githubusercontent.com/58107194/122784292-a342ae80-d2b2-11eb-81ce-cddb3ca10554.png)
_(For example, this is the URL you receive if you click the "Choose Version" button. The red text has to be removed in order for the link to work correctly)_
Kind regards
Jonas

**Comment by Eejit43** [comment]
This appears to have been fixed!

**Comment by LogischerJonasHD** [comment]
Indeed.
In that case, I can close this issue!
