### ISSUE TITLE
Shot issue

### ISSUE THREAD

**Issue by TerievWorks** [skyblock-wiki/skyblock-wiki.github.io#15]
When i press shot button i get
![image](https://user-images.githubusercontent.com/68177967/168624803-de10c448-fa1f-485b-9601-5751c3389395.png)
![1652713701647](https://user-images.githubusercontent.com/68177967/168624828-769a436e-55aa-41ea-bb78-bf7b56b63c2b.png)

**Comment by MonkeysHK** [comment]
What tool were you using? Please provide a way to recreate the issue.

**Comment by TerievWorks** [comment]
![image](https://user-images.githubusercontent.com/68177967/168785775-b2c77dc7-9aa8-40e3-808b-2b9dca0571f2.png)

**Comment by Eejit43** [comment]
What other mods are you using? There are known conflicts with mods such as Patcher.

**Comment by TerievWorks** [comment]
I'm using only wikitools. No other mods

**Comment by Eejit43** [comment]
Alright thanks, I'll pass this along and try to get this resolved

**Comment by Charzard4261** [comment]
Can you upload your latest.log to pastebin and post a link please Teriev?

**Comment by TerievWorks** [comment]
https://pastebin.com/fKCMkRmf

**Comment by Charzard4261** [comment]
Thanks, looking into it. Are you using MultiMC?

**Comment by TerievWorks** [comment]
Nah

**Comment by Charzard4261** [comment]
I think the issue is Optifine, I just tested and the issue was present with Optifine and gone without it. Try removing it, I can see you have it installed in the log.

**Comment by TerievWorks** [comment]
Tysm! Works now
