### ISSUE TITLE
Render from upload doesn't work

### ISSUE THREAD

**Issue by Uncursee** [skyblock-wiki/skyblock-wiki.github.io#6]
When I try to render from an upload the render of the head doesn't work but when I do the NBT Data or Texture ID works. 
![Screenshot_6](https://user-images.githubusercontent.com/41270826/125667648-fde11684-3479-48f1-90ee-b71b3a2e1beb.png)
This is what happens when I try with an upload after 5 minutes

**Comment by joker876** [comment]
@monkeysHK can you take care of this?

**Comment by joker876** [comment]
Also, @Uncurse, can you open your browser's console (in Chrome by pressing CTRL+Shift+i and navigating to the "console" tab) and tell us if there are any errors?

**Comment by MonkeysHK** [comment]
Thank you very much for reporting the issue. The mentioned issue should be fixed now. Please open a new issue if this problem persists.
